services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  backend:
    build: ./server
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata:
